# Server services are automatically launched with "docker compose up"
# Client apps can be lauched with "docker compose run --rm *service-name* *--args*"

# If client images are changed you need to run:
# sudo docker compose --profile clients build

services:
  # Server microservices
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Volume pgdata on the host
      - pgdata:/var/lib/postgresql
      # Bind mount, ./db-init is the folder location on the host
      - ./db-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-7000}:8080

  data-manager:
    build: ../datamanager/
    container_name: data-manager
    depends_on:
      - db
      - mosquitto
    environment: 
      POSTGRES_SMOKE_CONNECTION_STRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      MQTT_BROKER: tcp://mosquitto:1883
      MQTT_CLIENT_ID: data-manager
      MQTT_TOPIC: data-manager/raw-readings
    ports:
      - ${DATA_MANAGER_PORT:-7001}:8080

  gateway:
    build: ../gateway/Gateway/
    container_name: gateway
    depends_on:
      - data-manager
    environment:
      DATA_MANAGER_URL: http://data-manager:8080
    ports:
      - ${GATEWAY_PORT:-7002}:8080

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config

  event-manager:
    build: ../event-manager/
    container_name: event-manager
    depends_on:
      - data-manager
      - mosquitto
    environment:
      MQTT_BROKER: tcp://mosquitto:1883
      MQTT_CLIENT_ID: event-manager
      MQTT_SUBSCRIBE_TOPIC: data-manager/raw-readings
      MQTT_PUBLISH_TOPIC: event-manager/threshold-readings
      PM_25_THRESHOLD: ${PM_25_THRESHOLD:-50}
      TVOC_THRESHOLD: ${TVOC_THRESHOLD:-600}
      ECO2_THRESHOLD: ${ECO2_THRESHOLD:-2000}
      TEMPERATURE_THRESHOLD: ${TEMPERATURE_THRESHOLD:-50}


  # Client apps
  mqtt-client:
    build: ../mqtt-client/
    profiles: ["clients"]
    container_name: mqtt-client
    stdin_open: true            # docker run -i
    tty: true                   # docker run -t
    environment:
      MQTT_BROKER_ADDRESS: mosquitto
      MQTT_BROKER_PORT: 1883

  sensor-generator:
    build: ../sensor-generator/
    profiles: ["clients"]
    container_name: sensor-generator
    stdin_open: true            # docker run -i
    tty: true                   # docker run -t
    environment:
      GATEWAY_URL: http://gateway:8080


volumes:
  pgdata:
